import type { Product } from "@/contexts/app-context"

export const categories = [
  {
    id: "tools",
    nameRu: "Инструменты",
    nameUz: "Asboblar",
    icon: "🔨",
  },
  {
    id: "plumbing",
    nameRu: "Сантехника",
    nameUz: "Santexnika",
    icon: "🚿",
  },
  {
    id: "electrical",
    nameRu: "Электрика",
    nameUz: "Elektr",
    icon: "⚡",
  },
  {
    id: "paints",
    nameRu: "Краски",
    nameUz: "Bo'yoqlar",
    icon: "🎨",
  },
  {
    id: "building",
    nameRu: "Стройматериалы",
    nameUz: "Qurilish materiallari",
    icon: "🧱",
  },
  {
    id: "garden",
    nameRu: "Сад и огород",
    nameUz: "Bog' va poliz",
    icon: "🌱",
  },
]

export const brands = [
  "Bosch",
  "Makita",
  "DeWalt",
  "Hitachi",
  "Stanley",
  "Black & Decker",
  "Grohe",
  "Hansgrohe",
  "Roca",
  "Ideal Standard",
  "Vitra",
  "Schneider Electric",
  "Legrand",
  "ABB",
  "Siemens",
  "Dulux",
  "Tikkurila",
  "Caparol",
  "Alpina",
  "Benjamin Moore",
]

export const mockProducts: Product[] = [
  {
    id: 1,
    name: {
      ru: "Дрель ударная Bosch GSB 13 RE",
      uz: "Bosch GSB 13 RE zarba matkap",
    },
    price: 450000,
    category: "tools",
    brand: "Bosch",
    rating: 4.8,
    inStock: true,
    isNew: false,
    description: {
      ru: "Профессиональная ударная дрель с высокой производительностью",
      uz: "Yuqori unumdorlikka ega professional zarba matkap",
    },
    specifications: {
      Мощность: "600 Вт",
      "Максимальный диаметр сверления": "13 мм",
      "Частота ударов": "44000 уд/мин",
      Вес: "1.8 кг",
    },
  },
  {
    id: 2,
    name: {
      ru: "Смеситель для кухни Grohe Eurosmart",
      uz: "Grohe Eurosmart oshxona aralashtirgichi",
    },
    price: 180000,
    category: "plumbing",
    brand: "Grohe",
    rating: 4.6,
    inStock: true,
    isNew: true,
    description: {
      ru: "Современный кухонный смеситель с поворотным изливом",
      uz: "Aylanuvchi tumshug'i bilan zamonaviy oshxona aralashtirgichi",
    },
    specifications: {
      Материал: "Латунь",
      Покрытие: "Хром",
      Высота: "31 см",
      Гарантия: "5 лет",
    },
  },
  {
    id: 3,
    name: {
      ru: "Краска водоэмульсионная Dulux 10л",
      uz: "Dulux suv emulsiyali bo'yoq 10l",
    },
    price: 120000,
    category: "paints",
    brand: "Dulux",
    rating: 4.4,
    inStock: true,
    isNew: false,
    discount: 15,
    description: {
      ru: "Высококачественная водоэмульсионная краска для внутренних работ",
      uz: "Ichki ishlar uchun yuqori sifatli suv emulsiyali bo'yoq",
    },
    specifications: {
      Объем: "10 л",
      Расход: "12-14 м²/л",
      "Время высыхания": "2-4 часа",
      Основа: "Водная",
    },
  },
  {
    id: 4,
    name: {
      ru: "Розетка с заземлением Schneider Electric",
      uz: "Schneider Electric yerga ulash bilan rozetka",
    },
    price: 25000,
    category: "electrical",
    brand: "Schneider Electric",
    rating: 4.7,
    inStock: true,
    isNew: false,
    description: {
      ru: "Надежная розетка с заземлением для безопасного подключения",
      uz: "Xavfsiz ulanish uchun yerga ulash bilan ishonchli rozetka",
    },
    specifications: {
      Напряжение: "220-250 В",
      Ток: "16 А",
      "Степень защиты": "IP20",
      Цвет: "Белый",
    },
  },
  {
    id: 5,
    name: {
      ru: "Шуруповерт аккумуляторный Makita DF331D",
      uz: "Makita DF331D akkumulyatorli vintgach",
    },
    price: 320000,
    category: "tools",
    brand: "Makita",
    rating: 4.9,
    inStock: true,
    isNew: true,
    description: {
      ru: "Компактный аккумуляторный шуруповерт для профессионального использования",
      uz: "Professional foydalanish uchun ixcham akkumulyatorli vintgach",
    },
    specifications: {
      Напряжение: "12 В",
      "Крутящий момент": "30 Нм",
      Патрон: "10 мм",
      "Время зарядки": "22 мин",
    },
  },
  {
    id: 6,
    name: {
      ru: "Унитаз напольный Roca Debba",
      uz: "Roca Debba pol hojatxonasi",
    },
    price: 850000,
    category: "plumbing",
    brand: "Roca",
    rating: 4.5,
    inStock: true,
    isNew: false,
    description: {
      ru: "Современный напольный унитаз с системой двойного слива",
      uz: "Ikki tomonlama oqim tizimi bilan zamonaviy pol hojatxonasi",
    },
    specifications: {
      Материал: "Санфарфор",
      Тип: "Напольный",
      Слив: "Двойной 3/6 л",
      Размеры: "65x36x78 см",
    },
  },
  {
    id: 7,
    name: {
      ru: "Плитка керамическая 30x30 см",
      uz: "Keramik plitka 30x30 sm",
    },
    price: 45000,
    category: "building",
    brand: "Керама Марацци",
    rating: 4.3,
    inStock: true,
    isNew: false,
    description: {
      ru: "Качественная керамическая плитка для пола и стен",
      uz: "Pol va devorlar uchun sifatli keramik plitka",
    },
    specifications: {
      Размер: "30x30 см",
      Толщина: "8 мм",
      "Класс износостойкости": "PEI IV",
      Поверхность: "Матовая",
    },
  },
  {
    id: 8,
    name: {
      ru: "Выключатель двухклавишный Legrand",
      uz: "Legrand ikki tugmali o'chirish",
    },
    price: 18000,
    category: "electrical",
    brand: "Legrand",
    rating: 4.6,
    inStock: true,
    isNew: false,
    description: {
      ru: "Надежный двухклавишный выключатель для управления освещением",
      uz: "Yoritishni boshqarish uchun ishonchli ikki tugmali o'chirish",
    },
    specifications: {
      Напряжение: "250 В",
      Ток: "10 А",
      "Количество клавиш": "2",
      Монтаж: "Скрытый",
    },
  },
  {
    id: 9,
    name: {
      ru: "Болгарка угловая DeWalt DWE4157",
      uz: "DeWalt DWE4157 burchakli bolg'arka",
    },
    price: 180000,
    category: "tools",
    brand: "DeWalt",
    rating: 4.7,
    inStock: true,
    isNew: false,
    description: {
      ru: "Мощная угловая шлифовальная машина для профессиональных работ",
      uz: "Professional ishlar uchun kuchli burchakli silliqlash mashinasi",
    },
    specifications: {
      Мощность: "900 Вт",
      "Диаметр диска": "125 мм",
      Обороты: "11000 об/мин",
      Вес: "1.8 кг",
    },
  },
  {
    id: 10,
    name: {
      ru: "Раковина керамическая Ideal Standard 60см",
      uz: "Ideal Standard keramik lavabo 60sm",
    },
    price: 420000,
    category: "plumbing",
    brand: "Ideal Standard",
    rating: 4.4,
    inStock: true,
    isNew: true,
    description: {
      ru: "Элегантная керамическая раковина для ванной комнаты",
      uz: "Hammom xonasi uchun nafis keramik lavabo",
    },
    specifications: {
      Материал: "Санфарфор",
      Ширина: "60 см",
      Глубина: "46 см",
      Тип: "Подвесная",
    },
  },
  {
    id: 11,
    name: {
      ru: "Обои виниловые на флизелиновой основе 10м",
      uz: "Flizelinli asosda vinil devor qog'ozi 10m",
    },
    price: 85000,
    category: "building",
    brand: "Erismann",
    rating: 4.2,
    inStock: true,
    isNew: false,
    description: {
      ru: "Качественные виниловые обои на флизелиновой основе",
      uz: "Flizelinli asosda sifatli vinil devor qog'ozi",
    },
    specifications: {
      Длина: "10 м",
      Ширина: "1.06 м",
      Основа: "Флизелин",
      Тип: "Под покраску",
    },
  },
  {
    id: 12,
    name: {
      ru: "Люстра потолочная LED 48W",
      uz: "LED 48W shift lyustrasi",
    },
    price: 350000,
    category: "electrical",
    brand: "Philips",
    rating: 4.8,
    inStock: true,
    isNew: true,
    description: {
      ru: "Современная LED люстра с пультом дистанционного управления",
      uz: "Masofadan boshqarish pulti bilan zamonaviy LED lyustra",
    },
    specifications: {
      Мощность: "48 Вт",
      "Световой поток": "4800 лм",
      "Цветовая температура": "3000-6500 К",
      Диаметр: "60 см",
    },
  },
]
